// react-hn/src/components/Feed/Feed.tsx
import { useParams, Link } from 'react-router-dom';
import { useFeed } from '../../hooks/useHackerNewsAPI';
import Item from '../Item/Item';
import Loader from '../Loader/Loader';
import ErrorMessage from '../ErrorMessage/ErrorMessage';
import './Feed.scss';

interface FeedProps {
  feedType: string;
}

export default function Feed({ feedType }: FeedProps) {
  const { page } = useParams<{ page: string }>();
  const pageNum = page ? parseInt(page, 10) : 1;
  const { items, error } = useFeed(feedType, pageNum);
  const listStart = (pageNum - 1) * 30 + 1;

  return (
    <div className="main-content">
      {!items && !error && <Loader />}
      {!items && error && <ErrorMessage message={error} />}

      {items && (
        <div>
          {feedType === 'jobs' && (
            <p className="job-header">
              These are jobs at startups that were funded by Y Combinator. You can also get a job at
              a YC startup through{' '}
              <a href="https://triplebyte.com/?ref=yc_jobs">Triplebyte</a>.
            </p>
          )}
          {feedType !== 'new' && (
            <ol className={feedType !== 'jobs' ? 'list-margin' : undefined} start={listStart}>
              {items.map(item => (
                <li key={item.id} className="post">
                  <Item item={item} />
                </li>
              ))}
            </ol>
          )}
          <div className="nav">
            {listStart !== 1 && (
              <Link to={`/${feedType}/${pageNum - 1}`} className="prev">
                ‹ Prev
              </Link>
            )}
            {items.length === 30 && (
              <Link to={`/${feedType}/${pageNum + 1}`} className="more">
                More ›
              </Link>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

// src/app/feeds/feed/feed.component.ts
import { Component, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';
import { ActivatedRoute } from '@angular/router';

import { HackerNewsAPIService } from '../../shared/services/hackernews-api.service';
import { Story } from '../../shared/models/story';

@Component({
  selector: 'app-feed',
  templateUrl: './feed.component.html',
  styleUrls: ['./feed.component.scss']
})

export class FeedComponent implements OnInit {
  typeSub: Subscription;
  pageSub: Subscription;
  items: Story[];
  feedType: string;
  pageNum: number;
  listStart: number;
  errorMessage = '';

  constructor(
    private _hackerNewsAPIService: HackerNewsAPIService,
    private route: ActivatedRoute
  ) { }

  ngOnInit() {
    this.typeSub = this.route
      .data
      .subscribe(data => {
        this.feedType = (data as any).feedType;
      });

    this.pageSub = this.route.params.subscribe(params => {
      this.pageNum = params['page'] ? +params['page'] : 1;
      this._hackerNewsAPIService.fetchFeed(this.feedType, this.pageNum)
        .subscribe(
          items => this.items = items,
          error => this.errorMessage = 'Could not load ' + this.feedType + ' stories.',
          () => {
            this.listStart = ((this.pageNum - 1) * 30) + 1;
            window.scrollTo(0, 0);
          }
        );
    });
  }
}

<div class="main-content">
  @if (!items && !errorMessage) {
    <app-loader></app-loader>
  }
  @if (!items && errorMessage !=='') {
    <app-error-message [message]="errorMessage"></app-error-message>
  }

  @if (items) {
    <div>
      @if (feedType === 'jobs') {
        <p class="job-header">
          These are jobs at startups that were funded by Y Combinator.
          You can also get a job at a YC startup through <a href="https://triplebyte.com/?ref=yc_jobs">Triplebyte</a>.
        </p>
      }
      @if (feedType !== 'new') {
        <ol [class.list-margin]="feedType !== 'jobs'" start="{{ listStart }}">
          @for (item of items; track item) {
            <li class="post">
              <app-item class="item-block" [item]="item"></app-item>
            </li>
          }
        </ol>
      }
      <div class="nav">
        @if (listStart !== 1) {
          <a [routerLink]="['/' + feedType, pageNum - 1]" routerLinkActive="active" class="prev">
            ‹ Prev
          </a>
        }
        @if (items.length === 30) {
          <a [routerLink]="['/' + feedType, pageNum + 1]" routerLinkActive="active" class="more">
            More ›
          </a>
        }
      </div>
    </div>
  }
</div>
