// react-hn/src/components/Item/Item.tsx
import { Link } from 'react-router-dom';
import { Story } from '../../models/types';
import { useSettings } from '../../hooks/useSettings';
import { formatCommentCount } from '../../utils/commentFormat';
import './Item.scss';

interface ItemProps {
  item: Story;
}

export default function Item({ item }: ItemProps) {
  const { settings } = useSettings();
  const hasUrl = item.url && item.url.indexOf('http') === 0;

  return (
    <div style={{ marginBottom: `${settings.listSpacing}px` }}>
      {hasUrl ? (
        <p>
          <a
            className="title"
            style={{ fontSize: `${settings.titleFontSize}px` }}
            href={item.url}
            target={settings.openLinkInNewTab ? '_blank' : undefined}
            rel={settings.openLinkInNewTab ? 'noopener' : undefined}
          >
            {item.title}
          </a>
          {item.domain && <span className="domain">({item.domain})</span>}
        </p>
      ) : (
        <p>
          <Link
            className="title"
            style={{ fontSize: `${settings.titleFontSize}px` }}
            to={`/item/${item.id}`}
          >
            {item.title}
          </Link>
        </p>
      )}
      <div className="subtext-palm">
        {item.type !== 'job' && (
          <div className="details">
            <span className="name">
              <Link to={`/user/${item.user}`}>{item.user}</Link>
            </span>
            <span className="right">{item.points} ★</span>
          </div>
        )}
        <div className="details">
          {item.time_ago}
          {item.type !== 'job' && (
            <Link to={`/item/${item.id}`} className="comment-number">
              {' '}
              • {formatCommentCount(item.comments_count)}
            </Link>
          )}
        </div>
      </div>
      <div className="subtext-laptop">
        {item.type !== 'job' && (
          <span>
            {item.points} points by <Link to={`/user/${item.user}`}>{item.user}</Link>
          </span>
        )}
        <span className={item.type !== 'job' ? 'item-details' : undefined}>
          {item.time_ago}
          {item.type !== 'job' && (
            <span>
              {' | '}
              <Link to={`/item/${item.id}`}>{formatCommentCount(item.comments_count)}</Link>
            </span>
          )}
        </span>
      </div>
    </div>
  );
}

// src/app/feeds/item/item.component.ts
import { Component, Input } from '@angular/core';
import { Story } from '../../shared/models/story';

import { SettingsService } from '../../shared/services/settings.service';
import { Settings } from '../../shared/models/settings';

@Component({
  selector: 'app-item',
  templateUrl: './item.component.html',
  styleUrls: ['./item.component.scss']
})
export class ItemComponent {
  @Input() item: Story;
  settings: Settings;

  constructor(private _settingsService: SettingsService) {
    this.settings = this._settingsService.settings;
  }

  get hasUrl(): boolean {
    return this.item.url.indexOf('http') === 0;
  }

}

<div [ngStyle]="{'margin-bottom': settings.listSpacing+'px'}">
  <p *ngIf="hasUrl">
    <a class="title" [ngStyle]="{'font-size': settings.titleFontSize+'px'}" href="{{item.url}}" [attr.target]="settings.openLinkInNewTab ? '_blank' : null" [attr.rel]="settings.openLinkInNewTab ? 'noopener' : null">
      {{item.title}}
    </a>
    <span *ngIf="item.domain" class="domain">({{item.domain}})</span>
    <span class="favorite-toggle" (click)="toggleFavorite($event)" [class.is-favorite]="isFavorite()">
      {{ isFavorite() ? '★' : '☆' }}
    </span>
  </p>
  <p *ngIf="!hasUrl">
    <a class="title" [ngStyle]="{'font-size': settings.titleFontSize+'px'}" [routerLink]="['/item', item.id]" routerLinkActive="active">
      {{item.title}}
    </a>
    <span class="favorite-toggle" (click)="toggleFavorite($event)" [class.is-favorite]="isFavorite()">
      {{ isFavorite() ? '★' : '☆' }}
    </span>
  </p>
  <div class="subtext-palm">
    <div class="details" *ngIf="item.type !== 'job'">
      <span class="name"><a [routerLink]="['/user', item.user]" routerLinkActive="active">{{item.user}}</a></span>
      <span class="right">{{item.points}} ★</span>
    </div>
    <div class="details">
    {{ item.time_ago }}
    <a [routerLink]="['/item', item.id]" routerLinkActive="active" class="comment-number" *ngIf="item.type !== 'job'"> •
      {{item.comments_count | comment }}
    </a>
    </div>
  </div>
  <div class="subtext-laptop">
    <span *ngIf="item.type !== 'job'">
      {{item.points}} points by
      <a [routerLink]="['/user', item.user]" routerLinkActive="active">{{item.user}}</a>
    </span>
    <span [class.item-details]="item.type !== 'job'">
      {{ item.time_ago }}
      <span *ngIf="item.type !== 'job'"> |
        <a [routerLink]="['/item', item.id]" routerLinkActive="active">
          {{item.comments_count | comment }}
        </a>
      </span>
    </span>
  </div>
</div>
