// src/app/core/header/header.component.ts
import { Component, inject } from '@angular/core';

import { SettingsService } from '../../shared/services/settings.service';
import { Settings } from '../../shared/models/settings';
import { RouterLink, RouterLinkActive } from '@angular/router';

import { SettingsComponent } from '../settings/settings.component';

@Component({
    selector: 'app-header',
    templateUrl: './header.component.html',
    styleUrls: ['./header.component.scss'],
    imports: [RouterLink, RouterLinkActive, SettingsComponent]
})
export class HeaderComponent {
  private _settingsService = inject(SettingsService);

  settings: Settings;

  constructor() {
    this.settings = this._settingsService.settings;
  }

  toggleSettings() {
    this._settingsService.toggleSettings();
  }

  scrollTop() {
    window.scrollTo(0, 0);
  }
}

<header>
    <div id="header">
      <a class="home-link" routerLink="/news/1" routerLinkActive="active" (click)="scrollTop()">
        <div class="logo-inner"></div>
        <img class="logo" src="assets/images/logo.svg" alt="Logo">
      </a>
      <div class="header-text">
        <div class="left">
          <span class="header-nav">
            <a routerLink="/news/1" routerLinkActive="active" (click)="scrollTop()">News</a>
              |
            <a routerLink="/newest/1" routerLinkActive="active" (click)="scrollTop()">Newest</a>
              |
            <a routerLink="/show/1" routerLinkActive="active" (click)="scrollTop()">Show</a>
              |
            <a routerLink="/ask/1" routerLinkActive="active" (click)="scrollTop()">Ask</a>
              |
            <a routerLink="/jobs/1" routerLinkActive="active" (click)="scrollTop()">Jobs</a>
          </span>
          <span class="search-box">
            <input type="text" [(ngModel)]="searchTerm" placeholder="Search stories..." (keyup.enter)="onSearch()">
            <button (click)="onSearch()">Search</button>
          </span>
        </div>
      </div>
      <div class="info">
        <img class="settings" src="assets/images/cog.svg" alt="Settings" (click)="toggleSettings()">
      </div>
    </div>
    <app-settings *ngIf="settings.showSettings"></app-settings>
  </header>

// react-hn/src/components/Header/Header.tsx
import { NavLink } from 'react-router-dom';
import { useSettings } from '../../hooks/useSettings';
import Settings from '../Settings/Settings';
import './Header.scss';

export default function Header() {
  const { settings, toggleSettings } = useSettings();

  const scrollTop = () => window.scrollTo(0, 0);

  return (
    <header>
      <div id="header">
        <NavLink className="home-link" to="/news/1" onClick={scrollTop}>
          <div className="logo-inner"></div>
          <img className="logo" src="/assets/images/logo.svg" alt="Logo" />
        </NavLink>
        <div className="header-text">
          <div className="left">
            <span className="header-nav">
              <NavLink to="/newest/1" onClick={scrollTop}>
                new
              </NavLink>
              {' | '}
              <NavLink to="/show/1" onClick={scrollTop}>
                show
              </NavLink>
              {' | '}
              <NavLink to="/ask/1" onClick={scrollTop}>
                ask
              </NavLink>
              {' | '}
              <NavLink to="/jobs/1" onClick={scrollTop}>
                jobs
              </NavLink>
            </span>
          </div>
        </div>
        <div className="info">
          <img
            className="settings"
            src="/assets/images/cog.svg"
            alt="Settings"
            onClick={toggleSettings}
          />
        </div>
      </div>
      {settings.showSettings && <Settings />}
    </header>
  );
}
